print(('James', 22) < ('happy','호수','산',1000))
print(('A','B','C') < ('해','달','별'))
print(('가','나','다') < ('강','날','단'))
print(('kim','park','lee') < ('son','jung','min'))
print((0,10,100) < (0, 1, 1000))